export { academicPeriodService } from './laravel/AcademicPeriod.service';
export { programService } from './laravel/Program.service';
export { universityService } from './laravel/University.service';
export { applicantService } from './laravel/Applicant.service';
export { bankService } from './laravel/Bank.service';
export { documentTypesService } from './laravel/DocumentTypes.service';
export { loginService } from './laravel/Login.service';
export { interviewerAvailabilitiesService } from './laravel/InterviewerAvailabilities.service';
export { interviewAppointmentService } from './laravel/InterviewAppointment.service';
