import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import {AuthProvider} from "@/components";
import {NotificationProvider} from "@/components/ui/notification-dialog";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
        <body className="font-sans bg-gradient-to-br from-slate-50 to-slate-100">
        <AuthProvider>
            <NotificationProvider>
                {children}
            </NotificationProvider>
        </AuthProvider>
        </body>
        </html>
    );
}
