// Exportaciones de interfaces
export * from './AcademicPeriod.interface';
export * from './Application.interface';
export * from './Bank.interface';
export * from './Document.interface';
export * from './DocumentType.interface';
export * from './Login.interface';
export * from './Program.interface';
export * from './University.interface';
export * from './InterviewerAvailability';
export * from './InterviewAppointment.interface';
